variable "aws_region" {
    description = "AWS region for all resources (Athena/Glue are regional)."
    type        = string
    default     = "us-east-1"
}

variable "suffix" {
    description = "Suffix appended to globally-unique resources (the S3 lake bucket). If empty, a random 8-char hex suffix is generated."
    type        = string
    default     = ""
}

variable "fivetran_aws_account_id" {
    description = "Fivetran's AWS account ID — trust principal for the Fivetran assume role."
    type        = string
    default     = "834469178297"
}

variable "fivetran_external_id" {
    description = "External ID generated by Fivetran on the destination setup screen. Paste verbatim."
    type        = string
    sensitive   = true
}

variable "dbt_iam_user_arn" {
    description = "ARN of the IAM user that the dbt runner uses to assume the keystone-odi-dbt role. e.g. arn:aws:iam::123456789012:user/dbt-runner"
    type        = string
}

variable "github_pages_origin" {
    description = "Origin for the GitHub Pages site that hosts the demo SPA — required for the lake CORS rule."
    type        = string
    default     = "https://fivetran-jasonchletsos.github.io"
}

variable "tags" {
    description = "Tags applied to every resource."
    type        = map(string)
    default = {
        Project = "SAP-ODI-Demo"
        Demo    = "Keystone Industries"
        Owner   = "SE-team"
    }
}
