name: 'sap_odi'
version: '1.0.0'
config-version: 2

profile: 'sap_odi'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_packages"

models:
    sap_odi:
        silver:
            +materialized: view
            +schema: silver
        gold:
            +materialized: table
            +table_type: iceberg
            +format: parquet
            +schema: gold

seeds:
    sap_odi:
        +schema: seeds

tests:
    +store_failures: true
    +schema: test_results
